var data = [
  {
    "ID": "1",
    "disc": "",
    "lemma": "-a",
    "etym": "Esperanto -a",
    "etycat": "esperanto, conlangs",
    "notes": "",
    "derive": "mea, tea, mesa, tesa",
    "cat": "",
    "pos": "pronominal suffiix",
    "def": "1. Forms the possessives of pronouns"
  },
  {
    "ID": "2",
    "disc": "",
    "lemma": "a",
    "etym": "many languages; see wiki for a list",
    "etycat": "many",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "conjunction",
    "def": "1. Connects two noun or verb phrases; and, as well as"
  },
  {
    "ID": "3",
    "disc": "",
    "lemma": "-aga",
    "etym": "aga",
    "etycat": "affixation",
    "notes": "",
    "derive": "kaga, laja, saga, maga",
    "cat": "",
    "pos": "correlative suffix",
    "def": "1. Forms correlatives of quantity; -many"
  },
  {
    "ID": "4",
    "disc": "1",
    "lemma": "aga",
    "etym": "Enets ага (aga)",
    "etycat": "enets, samoyedic, uralic",
    "notes": "the sense \"Jupiter\" comes from its size",
    "derive": "",
    "cat": "planets, astronomy, days of the week",
    "pos": "noun",
    "def": "1. (talkatel~) Jupiter; 2. (taga~) Thursday"
  },
  {
    "ID": "4",
    "disc": "2",
    "lemma": "aga",
    "etym": "Enets ага (aga)",
    "etycat": "enets, samoyedic, uralic",
    "notes": "",
    "derive": "",
    "cat": "size, amount",
    "pos": "adjective",
    "def": "3. great, big, huge, large; 4. many, a lot, much"
  },
  {
    "ID": "5",
    "disc": "",
    "lemma": "-aj",
    "etym": "-a",
    "etycat": "a priori",
    "notes": "unrelated to aj \"moon",
    "derive": "kaj, laj, saj, maj",
    "cat": "",
    "pos": "correlative suffix",
    "def": "1. Forms correlatives of possession; -one's, -thing's"
  },
  {
    "ID": "6",
    "disc": "",
    "lemma": "aj",
    "etym": "Turkish ay",
    "etycat": "turkish, turkic",
    "notes": "",
    "derive": "",
    "cat": "astronomy, time, days of the week",
    "pos": "noun",
    "def": "1. moon; 2. month; 3. (taga~) Monday"
  },
  {
    "ID": "7",
    "disc": "1",
    "lemma": "ak",
    "etym": "Turkish ak",
    "etycat": "turkish, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to turn white, become white"
  },
  {
    "ID": "7",
    "disc": "2",
    "lemma": "ak",
    "etym": "Turkish ak",
    "etycat": "turkish, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "2. to clean, purify, whiten"
  },
  {
    "ID": "7",
    "disc": "3",
    "lemma": "ak",
    "etym": "Turkish ak",
    "etycat": "turkish, turkic",
    "notes": "",
    "derive": "",
    "cat": "colors",
    "pos": "noun",
    "def": "3. white"
  },
  {
    "ID": "7",
    "disc": "4",
    "lemma": "ak",
    "etym": "Turkish ak",
    "etycat": "turkish, turkic",
    "notes": "does not refer to the skin tone",
    "derive": "",
    "cat": "colors",
    "pos": "adjective",
    "def": "4. white; 5. clean, pure"
  },
  {
    "ID": "8",
    "disc": "",
    "lemma": "akakia",
    "etym": "Ancient Greek ἀκακία (akakía)",
    "etycat": "ancient greek, greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "plants, trees, nature",
    "pos": "noun",
    "def": "1. acacia"
  },
  {
    "ID": "9",
    "disc": "1",
    "lemma": "al",
    "etym": "Korean 알다 (al-da)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "aligi, aligitel, alpi, alpitel, alasu",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to know, have knowledge of, understand; 2. to know someone, have met before; 3. to realize"
  },
  {
    "ID": "9",
    "disc": "2",
    "lemma": "al",
    "etym": "Korean 알다 (al-da)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "aligi, aligitel, alpi, alpitel, alasu",
    "cat": "",
    "pos": "verb, modal",
    "def": "4. to know how, can, able to; 5. to have the ability to; 6. to be allowed to, have permission, be permitted to"
  },
  {
    "ID": "9",
    "disc": "3",
    "lemma": "al",
    "etym": "Korean 알다 (al-da)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "aligi, aligitel, alpi, alpitel, alasu",
    "cat": "",
    "pos": "noun",
    "def": "7. knowledge, know-how; 8. information"
  },
  {
    "ID": "9",
    "disc": "4",
    "lemma": "al",
    "etym": "Korean 알다 (al-da)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "aligi, aligitel, alpi, alpitel, alasu",
    "cat": "",
    "pos": "adjective",
    "def": "9. informative"
  },
  {
    "ID": "9",
    "disc": "5",
    "lemma": "al",
    "etym": "Korean 알다 (al-da)",
    "etycat": "korean, koreanic",
    "notes": "can be translated as \"one will",
    "derive": "aligi, aligitel, alpi, alpitel, alasu",
    "cat": "",
    "pos": "interjection",
    "def": "10. Used to signify the speaker acknowledges what the listener has said, usually that the action will be carried out"
  },
  {
    "ID": "10",
    "disc": "",
    "lemma": "alasu",
    "etym": "al + -asu",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "school",
    "pos": "noun",
    "def": "1. learning material, textbook, learning resources"
  },
  {
    "ID": "11",
    "disc": "1",
    "lemma": "aligi",
    "etym": "al + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "aligitel",
    "cat": "school",
    "pos": "verb, ambi.",
    "def": "1. to teach, instruct"
  },
  {
    "ID": "11",
    "disc": "2",
    "lemma": "aligi",
    "etym": "al + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "aligitel",
    "cat": "school",
    "pos": "noun",
    "def": "2. teaching, instruction"
  },
  {
    "ID": "12",
    "disc": "",
    "lemma": "aligitel",
    "etym": "aligi + -tel",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "school, professions",
    "pos": "noun, gendered",
    "def": "1. teacher, instructor, tutor"
  },
  {
    "ID": "13",
    "disc": "",
    "lemma": "alin",
    "etym": "Manchu ᠠᠯᡳᠨ (alin)",
    "etycat": "manchu, tungusic",
    "notes": "",
    "derive": "",
    "cat": "geography",
    "pos": "noun",
    "def": "1. mountain, mountain range"
  },
  {
    "ID": "14",
    "disc": "",
    "lemma": "alkik",
    "etym": "Tamazight ⴰⵍⵅⵉⵅ (alkik)",
    "etycat": "central atlas tamazight, amazigh, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "geography",
    "pos": "noun",
    "def": "1. sand"
  },
  {
    "ID": "15",
    "disc": "1",
    "lemma": "alpi",
    "etym": "al + -pi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "alpitel",
    "cat": "school",
    "pos": "verb, ambi.",
    "def": "1. to learn, study, be taught"
  },
  {
    "ID": "15",
    "disc": "2",
    "lemma": "alpi",
    "etym": "al + -pi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "alpitel",
    "cat": "school",
    "pos": "noun",
    "def": "2. learning, study"
  },
  {
    "ID": "16",
    "disc": "",
    "lemma": "alpitel",
    "etym": "alpi + -tel",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "school",
    "pos": "noun, gendered",
    "def": "1. student, pupil, apprentice"
  },
  {
    "ID": "17",
    "disc": "",
    "lemma": "altan",
    "etym": "Buryat алтан (altan)",
    "etycat": "buryat, mongolic",
    "notes": "",
    "derive": "",
    "cat": "minerals",
    "pos": "noun",
    "def": "1. gold; 2. coin, hard currency"
  },
  {
    "ID": "18",
    "disc": "",
    "lemma": "amal",
    "etym": "Romani amal",
    "etycat": "romani, indo-aryan, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun, gendered",
    "def": "1. friend, compatriot, companion"
  },
  {
    "ID": "19",
    "disc": "1",
    "lemma": "amelika",
    "etym": "English America",
    "etycat": "english, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "continents, nations, languages",
    "pos": "noun",
    "def": "1. (din~) the Americas; 2. (kak~, din~) the United States; 3. (salam~) American; 4. (jati~) American English"
  },
  {
    "ID": "19",
    "disc": "2",
    "lemma": "amelika",
    "etym": "English America",
    "etycat": "english, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "nationalities",
    "pos": "adjective",
    "def": "5. American (i.e. from the USA)"
  },
  {
    "ID": "20",
    "disc": "1",
    "lemma": "anta",
    "etym": "Finnish antaa",
    "etycat": "finnish, finnic, uralic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ditrans., e-til",
    "def": "1. to give"
  },
  {
    "ID": "20",
    "disc": "2",
    "lemma": "anta",
    "etym": "Finnish antaa",
    "etycat": "finnish, finnic, uralic",
    "notes": "active counterpart of al \"to be allowed",
    "derive": "",
    "cat": "",
    "pos": "verb, modal",
    "def": "2. to let, allow, permit"
  },
  {
    "ID": "20",
    "disc": "3",
    "lemma": "anta",
    "etym": "Finnish antaa",
    "etycat": "finnish, finnic, uralic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "3. to distribute, give out, donate"
  },
  {
    "ID": "20",
    "disc": "4",
    "lemma": "anta",
    "etym": "Finnish antaa",
    "etycat": "finnish, finnic, uralic",
    "notes": "figurative",
    "derive": "",
    "cat": "",
    "pos": "verb, trans., no",
    "def": "4. to give way, surrender, give up"
  },
  {
    "ID": "21",
    "disc": "",
    "lemma": "anu",
    "etym": "Koryak ынну (ʔənnu)",
    "etycat": "koryak, chukotkan, chukotko-kamchatkan",
    "notes": "plural of ынныын (ʔənnəʔən)",
    "derive": "",
    "cat": "animals, water",
    "pos": "noun",
    "def": "1. fish"
  },
  {
    "ID": "22",
    "disc": "",
    "lemma": "asak",
    "etym": "Western Yugur azaq",
    "etycat": "western yugur, turkic",
    "notes": "",
    "derive": "",
    "cat": "body",
    "pos": "noun",
    "def": "1. foot"
  },
  {
    "ID": "23",
    "disc": "",
    "lemma": "asan",
    "etym": "Persian آسان (âsân)",
    "etycat": "persian, iranian, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "1. light, lightweight; 2. easy"
  },
  {
    "ID": "24",
    "disc": "",
    "lemma": "-asu",
    "etym": "asu",
    "etycat": "affixation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "nominal suffix",
    "def": "1. Creates nouns for a group or collection of something"
  },
  {
    "ID": "25",
    "disc": "1",
    "lemma": "asu",
    "etym": "Burmese အစု (a.cu.)",
    "etycat": "burmese, lolo-burmese, tibeto-burman, sino-tibetan",
    "notes": "",
    "derive": "-asu",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to group together, collect, coalesce"
  },
  {
    "ID": "25",
    "disc": "2",
    "lemma": "asu",
    "etym": "Burmese အစု (a.cu.)",
    "etycat": "burmese, lolo-burmese, tibeto-burman, sino-tibetan",
    "notes": "",
    "derive": "-asu",
    "cat": "",
    "pos": "verb, intr.",
    "def": "2. to concentrate, focus"
  },
  {
    "ID": "25",
    "disc": "3",
    "lemma": "asu",
    "etym": "Burmese အစု (a.cu.)",
    "etycat": "burmese, lolo-burmese, tibeto-burman, sino-tibetan",
    "notes": "",
    "derive": "-asu",
    "cat": "mathematics",
    "pos": "noun",
    "def": "3. group, collection; 4. small community, tribe; 5. belongings; 6. stock, inventory; 7. (mathematics) set"
  },
  {
    "ID": "26",
    "disc": "1",
    "lemma": "at",
    "etym": "Korean -었- (-eot-)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "particle",
    "def": "1. Forms the perfect aspect, analogous to have-support in English."
  },
  {
    "ID": "26",
    "disc": "2",
    "lemma": "at",
    "etym": "Korean -었- (-eot-)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "interjection",
    "def": "2. General affirmative answer in the perfect; yes"
  },
  {
    "ID": "27",
    "disc": "1",
    "lemma": "ataf",
    "etym": "Hebrew עטף (ataf)",
    "etycat": "hebrew, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to wrap, cover, package; 2. to wrap around, enclose"
  },
  {
    "ID": "27",
    "disc": "2",
    "lemma": "ataf",
    "etym": "Hebrew עטף (ataf)",
    "etycat": "hebrew, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "3. wrapping, packaging, covering"
  },
  {
    "ID": "28",
    "disc": "",
    "lemma": "atasi",
    "etym": "Georgian ათასი (atasi)",
    "etycat": "georgian, kartvelian",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. thousand, one thousand; 2. (ordinal) thousandth"
  },
  {
    "ID": "29",
    "disc": "1",
    "lemma": "aveli",
    "etym": "Armenian ավելի (aveli)",
    "etycat": "armenian, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "particle",
    "def": "1. Used to form the comparative"
  },
  {
    "ID": "29",
    "disc": "2",
    "lemma": "aveli",
    "etym": "Armenian ավելի (aveli)",
    "etycat": "armenian, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "2. more; 3. to a greater extent"
  },
  {
    "ID": "30",
    "disc": "1",
    "lemma": "avelis",
    "etym": "aveli + -s",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "particle",
    "def": "1. Used to form the superlative"
  },
  {
    "ID": "30",
    "disc": "2",
    "lemma": "avelis",
    "etym": "aveli + -s",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "2. most; 3. to the greatest extent"
  },
  {
    "ID": "31",
    "disc": "",
    "lemma": "bak",
    "etym": "Cantonese 百 (baak3)",
    "etycat": "cantonese, sinitic, sino-tibetan",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. hundred, one hundred"
  },
  {
    "ID": "32",
    "disc": "1",
    "lemma": "balva",
    "etym": "Northern Sami balva",
    "etycat": "northern sami, sami, uralic",
    "notes": "",
    "derive": "",
    "cat": "weather",
    "pos": "verb, avalent",
    "def": "1. to be cloudy, be foggy"
  },
  {
    "ID": "32",
    "disc": "2",
    "lemma": "balva",
    "etym": "Northern Sami balva",
    "etycat": "northern sami, sami, uralic",
    "notes": "alternatively, balvapi",
    "derive": "",
    "cat": "",
    "pos": "verb, intransitive",
    "def": "2. to cloud up, become foggy"
  },
  {
    "ID": "32",
    "disc": "3",
    "lemma": "balva",
    "etym": "Northern Sami balva",
    "etycat": "northern sami, sami, uralic",
    "notes": "",
    "derive": "",
    "cat": "weather, astronomy, planets",
    "pos": "noun",
    "def": "3. cloud, fog; 4. (talkatel~) Uranus"
  },
  {
    "ID": "33",
    "disc": "1",
    "lemma": "banyak",
    "etym": "Indonesian banyak",
    "etycat": "indonesian, malayo-polynesian, austronesian",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb",
    "def": "1. to count, enumerate"
  },
  {
    "ID": "33",
    "disc": "2",
    "lemma": "banyak",
    "etym": "Indonesian banyak",
    "etycat": "indonesian, malayo-polynesian, austronesian",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. number"
  },
  {
    "ID": "34",
    "disc": "",
    "lemma": "basa",
    "etym": "Sanskrit भाषा (bhāṣā) and descendants",
    "etycat": "sanskrit, indo-aryan, indo-european",
    "notes": "",
    "derive": "baslamo",
    "cat": "languages",
    "pos": "noun",
    "def": "1. language"
  },
  {
    "ID": "35",
    "disc": "",
    "lemma": "baslamo",
    "etym": "basa + salam",
    "etycat": "a priori, portmanteau, compound",
    "notes": "ending -o is a leftover from part of speech suffixes",
    "derive": "",
    "cat": "languages",
    "pos": "noun",
    "def": "1. (jati~) Baslamo; 2. (salam~) someone who speaks Baslamo; 3. (din~) the places Baslamo is spoken"
  },
  {
    "ID": "36",
    "disc": "",
    "lemma": "bilu",
    "etym": "Kannada ಬೀಳು (bīḷu)",
    "etycat": "kannada, south dravidian, dravidian",
    "notes": "",
    "derive": "bilupuka",
    "cat": "food",
    "pos": "verb, intr.",
    "def": "1. to fall down, fall; 2. to collapse from exhaustion; 3. to spoil (of food); 4. (figuratively) to die"
  },
  {
    "ID": "37",
    "disc": "",
    "lemma": "bilupuka",
    "etym": "bilu + puka",
    "etycat": "german, germanic, indo-european, compound, lexical compound",
    "notes": "calque of German Falltür",
    "derive": "",
    "cat": "buildings",
    "pos": "noun",
    "def": "1. trapdoor, hatch; 2. an opening in a floor or ceiling to allow smth. through (e.g. a skylight); 3. window"
  },
  {
    "ID": "38",
    "disc": "",
    "lemma": "bjal",
    "etym": "Korean 별 (byeol)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "",
    "cat": "astronomy",
    "pos": "noun",
    "def": "1. star; 2. star-shaped symbol"
  },
  {
    "ID": "39",
    "disc": "1",
    "lemma": "bo",
    "etym": "Vietnamese bó",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to bundle up; 2. to package; 3. to tie"
  },
  {
    "ID": "39",
    "disc": "2",
    "lemma": "bo",
    "etym": "Vietnamese bó",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "4. bundle, package, bunch; 5. box, container"
  },
  {
    "ID": "40",
    "disc": "",
    "lemma": "bol",
    "etym": "English bowl",
    "etycat": "english, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "cooking",
    "pos": "noun",
    "def": "1. bowl"
  },
  {
    "ID": "41",
    "disc": "",
    "lemma": "bumi",
    "etym": "Hindi भूमि (bhūmi)",
    "etycat": "hindi, indo-aryan, indo-european",
    "notes": "",
    "derive": "",
    "cat": "astronomy, planets, Earth, nature",
    "pos": "noun",
    "def": "1. Earth; 2. land, soil"
  },
  {
    "ID": "42",
    "disc": "",
    "lemma": "da",
    "etym": "Telugu డా (ḍā)",
    "etycat": "telugu, south dravidian, dravidian",
    "notes": "when one faces where the sun rises, north is to the left",
    "derive": "",
    "cat": "directions, cardinal directions",
    "pos": "preposition",
    "def": "1. left, leftwards; 2. north"
  },
  {
    "ID": "43",
    "disc": "1",
    "lemma": "dan",
    "etym": "Vietnamese đánh, đấm, đá, đập",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "violence",
    "pos": "verb, ambi.",
    "def": "1. to engage in combat, fight, battle; 2. to hit, punch, kick, attack"
  },
  {
    "ID": "43",
    "disc": "2",
    "lemma": "dan",
    "etym": "Vietnamese đánh, đấm, đá, đập",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "sports",
    "pos": "verb, trans.",
    "def": "3. to play a sport that involves hitting an object"
  },
  {
    "ID": "43",
    "disc": "3",
    "lemma": "dan",
    "etym": "Vietnamese đánh, đấm, đá, đập",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "linguistics, technology",
    "pos": "verb, intr.",
    "def": "4. (linguistics) to tap, flap; 5. (technology) to type"
  },
  {
    "ID": "43",
    "disc": "4",
    "lemma": "dan",
    "etym": "Vietnamese đánh, đấm, đá, đập",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "violence, linguistics, technology",
    "pos": "noun",
    "def": "6. fight, brawl, combat; 7. battle, struggle; 8. punch, hit, kick, attack; 9. match (of a game); 10. (linguistics) tap, flap; 11. (technology) keystroke"
  },
  {
    "ID": "43",
    "disc": "5",
    "lemma": "dan",
    "etym": "Vietnamese đánh, đấm, đá, đập",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "violence, linguistics",
    "pos": "adjective",
    "def": "12. violent, combative; 13. (linguistics) tapped, flapped (as in articulation)"
  },
  {
    "ID": "44",
    "disc": "1",
    "lemma": "dat",
    "etym": "Korean 닫다 (datda)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to close, shut down; 2. to shut (one's mouth); 3. to disable"
  },
  {
    "ID": "44",
    "disc": "2",
    "lemma": "dat",
    "etym": "Korean 닫다 (datda)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "",
    "cat": "business",
    "pos": "verb, intr.",
    "def": "4. to close (of a business)"
  },
  {
    "ID": "44",
    "disc": "3",
    "lemma": "dat",
    "etym": "Korean 닫다 (datda)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "",
    "cat": "internet",
    "pos": "adjective",
    "def": "5. closed; 6. disabled, off; 7. unavailable, offline"
  },
  {
    "ID": "45",
    "disc": "1",
    "lemma": "defi",
    "etym": "French défi",
    "etycat": "french, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to challenge, trial, summon, call forth"
  },
  {
    "ID": "45",
    "disc": "2",
    "lemma": "defi",
    "etym": "French défi",
    "etycat": "french, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. challenge, trial"
  },
  {
    "ID": "46",
    "disc": "",
    "lemma": "din",
    "etym": "Thai ดิน (din)",
    "etycat": "thai, southwestern thai, kra-dai",
    "notes": "",
    "derive": "dinele, -idi",
    "cat": "Earth",
    "pos": "noun",
    "def": "1. nation, state, country; 2. land, area, region"
  },
  {
    "ID": "47",
    "disc": "",
    "lemma": "dolo",
    "etym": "Manchu ᡩᠣᠯᠣ (dolo)",
    "etycat": "manchu, tungusic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "preposition",
    "def": "1. inside, interior, in"
  },
  {
    "ID": "48",
    "disc": "1",
    "lemma": "dop",
    "etym": "Korean 돕다 (dopda)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "dopel",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to help, aid, assist"
  },
  {
    "ID": "48",
    "disc": "2",
    "lemma": "dop",
    "etym": "Korean 돕다 (dopda)",
    "etycat": "korean, koreanic",
    "notes": "",
    "derive": "dopel",
    "cat": "",
    "pos": "verb, trans.",
    "def": "2. to serve, wait"
  },
  {
    "ID": "49",
    "disc": "1",
    "lemma": "dopel",
    "etym": "dop + -tel",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "professions",
    "pos": "noun, gendered",
    "def": "1. helper, one who aides; 2. server, waiter"
  },
  {
    "ID": "49",
    "disc": "2",
    "lemma": "dopel",
    "etym": "dop + -tel",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "technology",
    "pos": "noun",
    "def": "3. (computing) server"
  },
  {
    "ID": "50",
    "disc": "",
    "lemma": "doska",
    "etym": "Slovak doska",
    "etycat": "slovak, slavic, indo-european",
    "notes": "",
    "derive": "doskapatal",
    "cat": "",
    "pos": "noun",
    "def": "1. plank, board; 2. table; 3. tablet"
  },
  {
    "ID": "51",
    "disc": "",
    "lemma": "doskapatal",
    "etym": "doska + patal",
    "etycat": "compound, lexical compound",
    "notes": "",
    "derive": "",
    "cat": "minerals",
    "pos": "noun",
    "def": "1. slate, shale; 2. tiles, shingles"
  },
  {
    "ID": "52",
    "disc": "1",
    "lemma": "dostep",
    "etym": "Polish dostęp",
    "etycat": "polish, slavic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to access, approach, obtain"
  },
  {
    "ID": "52",
    "disc": "2",
    "lemma": "dostep",
    "etym": "Polish dostęp",
    "etycat": "polish, slavic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. accessibility"
  },
  {
    "ID": "52",
    "disc": "3",
    "lemma": "dostep",
    "etym": "Polish dostęp",
    "etycat": "polish, slavic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "3. accessible"
  },
  {
    "ID": "53",
    "disc": "1",
    "lemma": "dulum",
    "etym": "Hiligaynon dulum",
    "etycat": "hiligaynon, malayo-polynesian, austronesian",
    "notes": "",
    "derive": "",
    "cat": "time, colors",
    "pos": "noun",
    "def": "1. night; 2. black"
  },
  {
    "ID": "53",
    "disc": "2",
    "lemma": "dulum",
    "etym": "Hiligaynon dulum",
    "etycat": "hiligaynon, malayo-polynesian, austronesian",
    "notes": "",
    "derive": "",
    "cat": "colors",
    "pos": "adjective",
    "def": "3. dark, gloomy; 4. black"
  },
  {
    "ID": "54",
    "disc": "1",
    "lemma": "ega",
    "etym": "German Ärger",
    "etycat": "german, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to be frustrated, be angry"
  },
  {
    "ID": "54",
    "disc": "2",
    "lemma": "ega",
    "etym": "German Ärger",
    "etycat": "german, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "emotions",
    "pos": "noun",
    "def": "2. anger, frustration"
  },
  {
    "ID": "54",
    "disc": "3",
    "lemma": "ega",
    "etym": "German Ärger",
    "etycat": "german, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "3. angry; 4. annoying, frustrating"
  },
  {
    "ID": "55",
    "disc": "",
    "lemma": "ek",
    "etym": "Swedish ek",
    "etycat": "swedish, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. oak, member of the genus Quercus"
  },
  {
    "ID": "56",
    "disc": "",
    "lemma": "-el",
    "etym": "a priori",
    "etycat": "a priori",
    "notes": "coincidentally similar to the agentive suffix -tel",
    "derive": "kel, lel, sel, mel",
    "cat": "",
    "pos": "correlative suffix",
    "def": "1. Forms demonstrative determiner-pronoun correlatives"
  },
  {
    "ID": "57",
    "disc": "",
    "lemma": "-el",
    "etym": "-tel",
    "etycat": "alternative forms",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "nominal suffix",
    "def": "1. Alternative form of -tel used after some consonants"
  },
  {
    "ID": "58",
    "disc": "",
    "lemma": "ele",
    "etym": "Kannada ಎಲೆ (ele)",
    "etycat": "kannada, south dravidian, dravidian",
    "notes": "",
    "derive": "dinele",
    "cat": "nature",
    "pos": "noun",
    "def": "1. leaf; 2. sheet (of paper); 3. sail; 4. bush"
  },
  {
    "ID": "59",
    "disc": "",
    "lemma": "dinele",
    "etym": "din + ele",
    "etycat": "compound, lexical compound",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. map"
  },
  {
    "ID": "60",
    "disc": "",
    "lemma": "-epi",
    "etym": "-pi",
    "etycat": "alternative forms",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verbal suffix",
    "def": "1. Allomorph of -pi used after some consonants"
  },
  {
    "ID": "61",
    "disc": "1",
    "lemma": "esa",
    "etym": "German essen",
    "etycat": "german, germanic, indo-european",
    "notes": "",
    "derive": "esagi",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to eat, drink, consume"
  },
  {
    "ID": "61",
    "disc": "2",
    "lemma": "esa",
    "etym": "German essen",
    "etycat": "german, germanic, indo-european",
    "notes": "",
    "derive": "esagi",
    "cat": "food, drink",
    "pos": "noun",
    "def": "2. food, drink, sustenance; 3. meal"
  },
  {
    "ID": "62",
    "disc": "",
    "lemma": "esagi",
    "etym": "esa + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambidi., e-til",
    "def": "1. to feed, make drink"
  },
  {
    "ID": "63",
    "disc": "",
    "lemma": "eski",
    "etym": "Kyrgyz эски (eski)",
    "etycat": "kyrgyz, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "1. old, old-fashioned, out of date; 2. expired"
  },
  {
    "ID": "64",
    "disc": "1",
    "lemma": "fas",
    "etym": "Portuguese fazer",
    "etycat": "portuguese, romance, indo-european",
    "notes": "",
    "derive": "fasono, fastel",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to make, create; 2. to do, carry out, perform; 3. to use, utilize"
  },
  {
    "ID": "64",
    "disc": "2",
    "lemma": "fas",
    "etym": "Portuguese fazer",
    "etycat": "portuguese, romance, indo-european",
    "notes": "",
    "derive": "fasono, fastel",
    "cat": "technology",
    "pos": "verb, trans., sima",
    "def": "4. to overwrite"
  },
  {
    "ID": "64",
    "disc": "3",
    "lemma": "fas",
    "etym": "Portuguese fazer",
    "etycat": "portuguese, romance, indo-european",
    "notes": "",
    "derive": "fasono, fastel",
    "cat": "",
    "pos": "noun",
    "def": "5. activity, performance; 6. creation; 7. usage"
  },
  {
    "ID": "65",
    "disc": "1",
    "lemma": "fasono",
    "etym": "fas + ono",
    "etycat": "compound, lexical compound",
    "notes": "",
    "derive": "",
    "cat": "robotics",
    "pos": "verb, ambi.",
    "def": "1. to perform automatically"
  },
  {
    "ID": "65",
    "disc": "2",
    "lemma": "fasono",
    "etym": "fas + ono",
    "etycat": "compound, lexical compound",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "2. to carry out alone"
  },
  {
    "ID": "65",
    "disc": "3",
    "lemma": "fasono",
    "etym": "fas + ono",
    "etycat": "compound, lexical compound",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "3. automatic"
  },
  {
    "ID": "66",
    "disc": "",
    "lemma": "fastel",
    "etym": "fas + -tel",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "religion",
    "pos": "noun",
    "def": "1. creator, maker; 2. user; 3. (figuratively) God"
  },
  {
    "ID": "67",
    "disc": "1",
    "lemma": "fok",
    "etym": "Hungarian fog",
    "etycat": "hungarian, ugric, uralic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to bite"
  },
  {
    "ID": "67",
    "disc": "2",
    "lemma": "fok",
    "etym": "Hungarian fog",
    "etycat": "hungarian, ugric, uralic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. tooth; 3. cog; 4. tooth (of a saw)"
  },
  {
    "ID": "67",
    "disc": "3",
    "lemma": "fok",
    "etym": "Hungarian fog",
    "etycat": "hungarian, ugric, uralic",
    "notes": "",
    "derive": "",
    "cat": "linguistics",
    "pos": "adjective",
    "def": "5. serrated; 6. (linguistics) dental"
  },
  {
    "ID": "68",
    "disc": "1",
    "lemma": "fu",
    "etym": "onomatopoeic",
    "etycat": "onomatopoeia, a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, intr.",
    "def": "1. to blow, puff"
  },
  {
    "ID": "68",
    "disc": "2",
    "lemma": "fu",
    "etym": "onomatopoeic",
    "etycat": "onomatopoeia, a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "2. to fill with air"
  },
  {
    "ID": "69",
    "disc": "",
    "lemma": "ga",
    "etym": "Tày cạ",
    "etycat": "tày, central tai, kra-dai",
    "notes": "when used to relativize a verb's object, ga is put after the preposition, unless it is e, in which case ga replaces e",
    "derive": "",
    "cat": "",
    "pos": "particle",
    "def": "1. Introducing a clause that is the subject or object of a verb; 2. Introducing a relative clause that refers to something mentioned before; 3. Expressing a reason or cause for something"
  },
  {
    "ID": "70",
    "disc": "",
    "lemma": "gat",
    "etym": "Vietnamese gạch",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. brick, tile"
  },
  {
    "ID": "71",
    "disc": "",
    "lemma": "gata",
    "etym": "Cherokee ᎦᏔ (gata)",
    "etycat": "cherokee, iroquoian",
    "notes": "",
    "derive": "gatagi, ugata",
    "cat": "",
    "pos": "verb, intr.",
    "def": "1. to hang, suspend, float"
  },
  {
    "ID": "72",
    "disc": "",
    "lemma": "gatagi",
    "etym": "gata + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to hang up"
  },
  {
    "ID": "73",
    "disc": "",
    "lemma": "e",
    "etym": "Toki Pona e",
    "etycat": "toki pona, conlangs",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "particle",
    "def": "1. The default object particle for all verbs"
  },
  {
    "ID": "74",
    "disc": "",
    "lemma": "gaxa",
    "etym": "Gurage gäčä",
    "etycat": "gurage, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. hyena, aardwolf"
  },
  {
    "ID": "75",
    "disc": "",
    "lemma": "-gi",
    "etym": "-igi",
    "etycat": "alternative forms",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "nominal suffix",
    "def": "1. Alternative form of -igi"
  },
  {
    "ID": "76",
    "disc": "",
    "lemma": "gia",
    "etym": "Georgian ღია (ɣia)",
    "etycat": "georgian, kartvelian",
    "notes": "",
    "derive": "giagi",
    "cat": "",
    "pos": "adjective",
    "def": "1. pale, light, bright"
  },
  {
    "ID": "77",
    "disc": "",
    "lemma": "giagi",
    "etym": "gia + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to brighten, make pale, make light"
  },
  {
    "ID": "78",
    "disc": "1",
    "lemma": "gida",
    "etym": "Hausa gida",
    "etycat": "hausa, chadic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, intr.",
    "def": "1. to live, survive, stay alive; 2. to be housed"
  },
  {
    "ID": "78",
    "disc": "2",
    "lemma": "gida",
    "etym": "Hausa gida",
    "etycat": "hausa, chadic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "3. house, home"
  },
  {
    "ID": "79",
    "disc": "",
    "lemma": "gugol",
    "etym": "Hungarian guggol",
    "etycat": "hungarian, ugric, uralic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb",
    "def": "1. to crouch, squat, crouch down"
  },
  {
    "ID": "80",
    "disc": "1",
    "lemma": "idaman",
    "etym": "Central Atlas Tamazight ⵉⴷⴰⵎⵎⵏ (idammn), Tashelhit idammn, Tarifit idammen",
    "etycat": "central atlas tamazight, tashelhit, tarifit, amazigh, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to let, draw blood"
  },
  {
    "ID": "80",
    "disc": "2",
    "lemma": "idaman",
    "etym": "Central Atlas Tamazight ⵉⴷⴰⵎⵎⵏ (idammn), Tashelhit idammn, Tarifit idammen",
    "etycat": "central atlas tamazight, tashelhit, tarifit, amazigh, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, intr.",
    "def": "2. to make bleed"
  },
  {
    "ID": "80",
    "disc": "3",
    "lemma": "idaman",
    "etym": "Central Atlas Tamazight ⵉⴷⴰⵎⵎⵏ (idammn), Tashelhit idammn, Tarifit idammen",
    "etycat": "central atlas tamazight, tashelhit, tarifit, amazigh, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "astronomy, planets, days of the week, colors",
    "pos": "noun",
    "def": "3. blood; 4. red; 5. (astronomy) (talkatel~) Mars; 6. (taga~) Tuesday"
  },
  {
    "ID": "80",
    "disc": "4",
    "lemma": "idaman",
    "etym": "Central Atlas Tamazight ⵉⴷⴰⵎⵎⵏ (idammn), Tashelhit idammn, Tarifit idammen",
    "etycat": "central atlas tamazight, tashelhit, tarifit, amazigh, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "colors",
    "pos": "adjective",
    "def": "7. red; 8. bloody"
  },
  {
    "ID": "81",
    "disc": "",
    "lemma": "-idi",
    "etym": "din",
    "etycat": "baslamo, a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative suffix",
    "def": "1. Forms correlatives of location; -where"
  },
  {
    "ID": "82",
    "disc": "",
    "lemma": "-igi",
    "etym": "Esperanto -igi",
    "etycat": "esperanto, conlangs",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verbal suffix",
    "def": "1. Forms causative or factitive verbs, indicating an action being done to something"
  },
  {
    "ID": "83",
    "disc": "",
    "lemma": "-ik",
    "etym": "Armenian -իկ (-ik), descendants of Proto-Slavic -ikъ",
    "etycat": "armenian, slavic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "nominal suffix",
    "def": "1. Forms diminutives"
  },
  {
    "ID": "84",
    "disc": "",
    "lemma": "ik",
    "etym": "-ik",
    "etycat": "back-formation",
    "notes": "",
    "derive": "",
    "cat": "size, amount",
    "pos": "adjective",
    "def": "1. small, little, tiny; 2. few, some, small amount"
  },
  {
    "ID": "85",
    "disc": "1",
    "lemma": "imut",
    "etym": "Indoesian imut",
    "etycat": "indonesian, malayo-polynesian, austronesian",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, intr.",
    "def": "1. to smile"
  },
  {
    "ID": "85",
    "disc": "2",
    "lemma": "imut",
    "etym": "Indoesian imut",
    "etycat": "indonesian, malayo-polynesian, austronesian",
    "notes": "",
    "derive": "",
    "cat": "emotions",
    "pos": "adjective",
    "def": "2. cute, charming, pretty; 3. good, wonderful, well; 4. happy"
  },
  {
    "ID": "86",
    "disc": "1",
    "lemma": "ina",
    "etym": "Yoruba iná",
    "etycat": "yoruba, volta-niger, atlantic-congo",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to burn"
  },
  {
    "ID": "86",
    "disc": "2",
    "lemma": "ina",
    "etym": "Yoruba iná",
    "etycat": "yoruba, volta-niger, atlantic-congo",
    "notes": "",
    "derive": "",
    "cat": "classical elements",
    "pos": "noun",
    "def": "2. fire"
  },
  {
    "ID": "86",
    "disc": "3",
    "lemma": "ina",
    "etym": "Yoruba iná",
    "etycat": "yoruba, volta-niger, atlantic-congo",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "3. on fire, aflame"
  },
  {
    "ID": "87",
    "disc": "",
    "lemma": "inon",
    "etym": "Mohawk í꞉non",
    "etycat": "mohawk, northern iroquois, iroquois",
    "notes": "",
    "derive": "",
    "cat": "distance",
    "pos": "preposition",
    "def": "1. far, far away, remote"
  },
  {
    "ID": "88",
    "disc": "1",
    "lemma": "intaneto",
    "etym": "Japanese インターネット (intānetto), from English internet",
    "etycat": "japanese, japonic, english, germanic, indo-european",
    "notes": "coined at a time where I was weirdly adverse to taking any words from English",
    "derive": "",
    "cat": "technology",
    "pos": "verb, intr.",
    "def": "1. to browse the Internet, surf the web, go online"
  },
  {
    "ID": "88",
    "disc": "2",
    "lemma": "intaneto",
    "etym": "Japanese インターネット (intānetto), from English internet",
    "etycat": "japanese, japonic, english, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. the Internet"
  },
  {
    "ID": "88",
    "disc": "3",
    "lemma": "intaneto",
    "etym": "Japanese インターネット (intānetto), from English internet",
    "etycat": "japanese, japonic, english, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "3. on the Internet, online"
  },
  {
    "ID": "89",
    "disc": "",
    "lemma": "isk",
    "etym": "Central Atlas Tamazight ⵉⵙⴽ (isk)",
    "etycat": "central atlas tamazight, amazigh, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "music, automotive, animals",
    "pos": "noun",
    "def": "1. horn, antler; 2. claw (of a crab); 3. (music, automotive) horn"
  },
  {
    "ID": "90",
    "disc": "1",
    "lemma": "iso",
    "etym": "Greek ίσο (íso)",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "mathematics",
    "pos": "verb, trans.",
    "def": "1. to be equal to, equivalent to, identical to"
  },
  {
    "ID": "90",
    "disc": "2",
    "lemma": "iso",
    "etym": "Greek ίσο (íso)",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "physics",
    "pos": "verb, intr.",
    "def": "2. to act justly, be just"
  },
  {
    "ID": "90",
    "disc": "3",
    "lemma": "iso",
    "etym": "Greek ίσο (íso)",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "politics, law",
    "pos": "noun",
    "def": "3. equality, fairness; 4. justice"
  },
  {
    "ID": "90",
    "disc": "4",
    "lemma": "iso",
    "etym": "Greek ίσο (íso)",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "politcs, law",
    "pos": "adjective",
    "def": "5. equal, equivalent, identical; 6. having equal rights; 7. even, level, flat; 8. just"
  },
  {
    "ID": "90",
    "disc": "5",
    "lemma": "iso",
    "etym": "Greek ίσο (íso)",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "mathematics, law",
    "pos": "conjunction",
    "def": "9. as if, as it were, in the same way as, just like; 10. naturally, as a consequence; 11. so that"
  },
  {
    "ID": "90",
    "disc": "6",
    "lemma": "iso",
    "etym": "Greek ίσο (íso)",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "discourse markers",
    "pos": "interjection",
    "def": "11. well, so, uh"
  },
  {
    "ID": "91",
    "disc": "1",
    "lemma": "ista",
    "etym": "Azerbaijani istəmək",
    "etycat": "azerbaijani, turkic",
    "notes": "",
    "derive": "",
    "cat": "emotions",
    "pos": "verb, trans.",
    "def": "1. to want, desire, wish for; 2. to love, be in love with, love to; 3. to request for, ask for, ask permission for"
  },
  {
    "ID": "91",
    "disc": "2",
    "lemma": "ista",
    "etym": "Azerbaijani istəmək",
    "etycat": "azerbaijani, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, modal",
    "def": "4. to want, to desire"
  },
  {
    "ID": "91",
    "disc": "3",
    "lemma": "ista",
    "etym": "Azerbaijani istəmək",
    "etycat": "azerbaijani, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "5. (usually with a possessive?) beloved, loved object, favorite thing"
  },
  {
    "ID": "92",
    "disc": "",
    "lemma": "ja",
    "etym": "Persian یا (yâ)",
    "etycat": "persian, iranian, indo-european",
    "notes": "",
    "derive": "",
    "cat": "logical operations",
    "pos": "conjunction",
    "def": "1. or"
  },
  {
    "ID": "93",
    "disc": "",
    "lemma": "isogi",
    "etym": "iso + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "physics",
    "pos": "verb, trans.",
    "def": "1. to balance; 2. to make equal"
  },
  {
    "ID": "94",
    "disc": "1",
    "lemma": "jan",
    "etym": "Vietnamese dành",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "fasonojan",
    "cat": "technology",
    "pos": "verb, trans.",
    "def": "1. to save up, reserve, put back; 2. (computing) to save (i.e. a file)"
  },
  {
    "ID": "94",
    "disc": "2",
    "lemma": "jan",
    "etym": "Vietnamese dành",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "fasonojan",
    "cat": "technology",
    "pos": "noun",
    "def": "3. reserve, savings, stock; 4. (computing) save file"
  },
  {
    "ID": "95",
    "disc": "",
    "lemma": "jap",
    "etym": "Khmer យ៉ាប់ (yap)",
    "etycat": "khmer, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "1. heavy; 2. difficult, hard, challenging"
  },
  {
    "ID": "96",
    "disc": "1",
    "lemma": "jaset",
    "etym": "Halkomelem yóthet",
    "etycat": "halkomelem, coast salish, salishan",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. (figuratively) to reduce or hinder, move backwards"
  },
  {
    "ID": "96",
    "disc": "2",
    "lemma": "jaset",
    "etym": "Halkomelem yóthet",
    "etycat": "halkomelem, coast salish, salishan",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "preposition",
    "def": "2. back, backside, backwards"
  },
  {
    "ID": "96",
    "disc": "3",
    "lemma": "jaset",
    "etym": "Halkomelem yóthet",
    "etycat": "halkomelem, coast salish, salishan",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "3. late, last, behind"
  },
  {
    "ID": "97",
    "disc": "1",
    "lemma": "jati",
    "etym": "Navajo yátiʼ",
    "etycat": "navajo, southern dené, dené",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to speak, talk, say, message, communicate"
  },
  {
    "ID": "97",
    "disc": "2",
    "lemma": "jati",
    "etym": "Navajo yátiʼ",
    "etycat": "navajo, southern dené, dené",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. speech, talk; 3. message, text, SMS"
  },
  {
    "ID": "98",
    "disc": "",
    "lemma": "leto",
    "etym": "Slovene lẹ́to",
    "etycat": "slovene, slavic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. year"
  },
  {
    "ID": "99",
    "disc": "",
    "lemma": "makanigi",
    "etym": "ma + kan + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to take off, remove, doff"
  },
  {
    "ID": "100",
    "disc": "1",
    "lemma": "lo",
    "etym": "Nuosu ꇇ (lot)",
    "etycat": "nuosu, lolo-burmese, tibeto-burman, sino-tibetan",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. hand, fist; 2. arm"
  },
  {
    "ID": "100",
    "disc": "2",
    "lemma": "lo",
    "etym": "Nuosu ꇇ (lot)",
    "etycat": "nuosu, lolo-burmese, tibeto-burman, sino-tibetan",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "3. five"
  },
  {
    "ID": "101",
    "disc": "",
    "lemma": "kil",
    "etym": "Volapük kil",
    "etycat": "volapük, constructed",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. three"
  },
  {
    "ID": "102",
    "disc": "1",
    "lemma": "jok",
    "etym": "Latin iocus",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to play"
  },
  {
    "ID": "102",
    "disc": "2",
    "lemma": "jok",
    "etym": "Latin iocus",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. game"
  },
  {
    "ID": "103",
    "disc": "",
    "lemma": "jokel",
    "etym": "jok + -tel",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. player"
  },
  {
    "ID": "104",
    "disc": "",
    "lemma": "jun",
    "etym": "Burmese ယုန် (yun)",
    "etycat": "burmese, lolo-burmese, tibeto-burman, sino-tibetan",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. rabbit, hare"
  },
  {
    "ID": "105",
    "disc": "",
    "lemma": "k-",
    "etym": "ka",
    "etycat": "baslamo, a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative prefix",
    "def": "1. Forms interrogative-existential correlatives"
  },
  {
    "ID": "106",
    "disc": "1",
    "lemma": "ka",
    "etym": "Japanese か (ka)",
    "etycat": "japanese, japonic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb",
    "def": "1. to question, ask"
  },
  {
    "ID": "106",
    "disc": "2",
    "lemma": "ka",
    "etym": "Japanese か (ka)",
    "etycat": "japanese, japonic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. question"
  },
  {
    "ID": "106",
    "disc": "3",
    "lemma": "ka",
    "etym": "Japanese か (ka)",
    "etycat": "japanese, japonic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "particle",
    "def": "3. Interrogative particle, used either at the beginning or end of a sentence"
  },
  {
    "ID": "107",
    "disc": "",
    "lemma": "lot",
    "etym": "Lao ລົດ (lot)",
    "etycat": "lao, lolo-burmese, tibeto-burman, sino-tibetan",
    "notes": "semantics influenced by Arabic مركب (markab)",
    "derive": "",
    "cat": "vehicles, animals",
    "pos": "noun",
    "def": "1. vehicle, car, bus, automobile, train; 2. ship, boat, vessel; 3. saddle; 4. anything upon which one rides (e.g. camel, horse), steed"
  },
  {
    "ID": "108",
    "disc": "",
    "lemma": "ugal-lot",
    "etym": "ugal + lot",
    "etycat": "compound, lexical compound",
    "notes": "",
    "derive": "",
    "cat": "vehicles",
    "pos": "noun",
    "def": "1. train"
  },
  {
    "ID": "109",
    "disc": "",
    "lemma": "kaf",
    "etym": "Wolof këf",
    "etycat": "wolof, west atlantic, atlantic-congo",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. thing, entity; 2. idea, thought"
  },
  {
    "ID": "110",
    "disc": "",
    "lemma": "kel",
    "etym": "k- + -el",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. (interrogative) what, who, which; 2. (existential) some, something, someone"
  },
  {
    "ID": "111",
    "disc": "",
    "lemma": "kaj",
    "etym": "k- + -aj",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. (interrogative) whose, whoever's; 2. (existential) someone's, somebody's, something's"
  },
  {
    "ID": "112",
    "disc": "",
    "lemma": "kaga",
    "etym": "k- + -aga",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. (interrogative) how much, how many; 2. (existential) some amount, some quantity of"
  },
  {
    "ID": "113",
    "disc": "",
    "lemma": "kom",
    "etym": "k- + om",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. (interrogative) why, for what reason, how, through what method; 2. (existential) for some reason, somehow, some way"
  },
  {
    "ID": "114",
    "disc": "",
    "lemma": "kosi",
    "etym": "k- + osi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. (interrogative) when, at what time; 2. (existential) sometime, sometimes"
  },
  {
    "ID": "115",
    "disc": "",
    "lemma": "kidi",
    "etym": "k- + -idi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. (interrogative) where; 2. (existential) somewhere"
  },
  {
    "ID": "116",
    "disc": "",
    "lemma": "lel",
    "etym": "l- + -el",
    "etycat": "compound, derivation",
    "notes": "used as a 3rd person pronoun",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. this, that, these, those, he, she, it, they"
  },
  {
    "ID": "117",
    "disc": "",
    "lemma": "laj",
    "etym": "l- + -aj",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. this/that person's, their, his, her, its"
  },
  {
    "ID": "118",
    "disc": "",
    "lemma": "laga",
    "etym": "l- + -aga",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. this/that much, this/that many"
  },
  {
    "ID": "119",
    "disc": "",
    "lemma": "lom",
    "etym": "l- + om",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. for this reason, because; 2. this way, this method"
  },
  {
    "ID": "120",
    "disc": "",
    "lemma": "losi",
    "etym": "l- + osi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. at this time, now, then, that time"
  },
  {
    "ID": "121",
    "disc": "",
    "lemma": "lidi",
    "etym": "l- + -idi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. here, there"
  },
  {
    "ID": "122",
    "disc": "",
    "lemma": "sel",
    "etym": "s- + -el",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. every, each"
  },
  {
    "ID": "123",
    "disc": "",
    "lemma": "saj",
    "etym": "s- + -aj",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. everyone's, everybody's (i.e. belong to every person)"
  },
  {
    "ID": "124",
    "disc": "",
    "lemma": "saga",
    "etym": "s- + -aga",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. all, whole"
  },
  {
    "ID": "125",
    "disc": "",
    "lemma": "som",
    "etym": "s- + om",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. for every reason, in any case, regardless"
  },
  {
    "ID": "126",
    "disc": "",
    "lemma": "sosi",
    "etym": "s- + osi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. all the time, every time, forever"
  },
  {
    "ID": "127",
    "disc": "",
    "lemma": "sidi",
    "etym": "s- + -idi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. everywhere"
  },
  {
    "ID": "128",
    "disc": "",
    "lemma": "mel",
    "etym": "m- + -el",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. none, nothing, nobody"
  },
  {
    "ID": "129",
    "disc": "",
    "lemma": "maj",
    "etym": "m- + -aj",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. nobody's, belonging to no-one"
  },
  {
    "ID": "130",
    "disc": "",
    "lemma": "maga",
    "etym": "m- + -aga",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. zero, none, nothing (amount)"
  },
  {
    "ID": "131",
    "disc": "",
    "lemma": "mom",
    "etym": "m- + om",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. for no reason; 2. with no method"
  },
  {
    "ID": "132",
    "disc": "",
    "lemma": "mosi",
    "etym": "m- + osi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. at no time, never"
  },
  {
    "ID": "133",
    "disc": "",
    "lemma": "midi",
    "etym": "m- + -idi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative",
    "def": "1. nowhere"
  },
  {
    "ID": "134",
    "disc": "1",
    "lemma": "kak",
    "etym": "O'odham ke꞉k \"to stand",
    "etycat": "o'odham, tepiman, uto-aztecan",
    "notes": "semantic loan from Romance languages to mean \"state, polity",
    "derive": "kakigi, kakepi",
    "cat": "",
    "pos": "verb, intr.",
    "def": "1. to be standing, stand straight, be upright; 2. to exist, be; 3. to stay, keep a certain state; 4. to be still, stay still"
  },
  {
    "ID": "134",
    "disc": "2",
    "lemma": "kak",
    "etym": "O'odham ke꞉k \"to stand",
    "etycat": "o'odham, tepiman, uto-aztecan",
    "notes": "used like German da steht or English it says, of a sign or other display",
    "derive": "kakigi, kakepi",
    "cat": "",
    "pos": "verb, trans.",
    "def": "4. to show, say, display"
  },
  {
    "ID": "134",
    "disc": "3",
    "lemma": "kak",
    "etym": "O'odham ke꞉k \"to stand",
    "etycat": "o'odham, tepiman, uto-aztecan",
    "notes": "",
    "derive": "kakigi, kakepi",
    "cat": "",
    "pos": "verb, trans., u",
    "def": "5. to stay at"
  },
  {
    "ID": "134",
    "disc": "4",
    "lemma": "kak",
    "etym": "O'odham ke꞉k \"to stand",
    "etycat": "o'odham, tepiman, uto-aztecan",
    "notes": "",
    "derive": "kakigi, kakepi",
    "cat": "technology, politics",
    "pos": "noun",
    "def": "6. status, standing, state of affairs; 7. online status; 8. state, polity"
  },
  {
    "ID": "135",
    "disc": "",
    "lemma": "kakigi",
    "etym": "kak + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to stand up, prop up; 2. to stop"
  },
  {
    "ID": "136",
    "disc": "",
    "lemma": "kakepi",
    "etym": "kak + -epi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, intr.",
    "def": "1. to stand, begin standing; 2. to be stopped, to stop"
  },
  {
    "ID": "137",
    "disc": "1",
    "lemma": "kam",
    "etym": "Khmer កាំ (kam)",
    "etycat": "khmer, austroasiatic",
    "notes": "semantically influenced by Gujarati પેઢી (peḍhī)",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. step, rung (of a ladder, stairs, etc.); 2. stroke, line; 3. generation; 4. lineage"
  },
  {
    "ID": "137",
    "disc": "2",
    "lemma": "kam",
    "etym": "Khmer កាំ (kam)",
    "etycat": "khmer, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "5. straight, linear"
  },
  {
    "ID": "138",
    "disc": "1",
    "lemma": "kan",
    "etym": "Khmer កាន់ (kan)",
    "etycat": "khmer, austroasiatic",
    "notes": "",
    "derive": "makanigi",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to have, possess, be in possession of; 2. to carry, hold, grasp; 3. to grab, grasp"
  },
  {
    "ID": "138",
    "disc": "2",
    "lemma": "kan",
    "etym": "Khmer កាន់ (kan)",
    "etycat": "khmer, austroasiatic",
    "notes": "",
    "derive": "makanigi",
    "cat": "",
    "pos": "verb, trans., u",
    "def": "4. to keep in a certain state; 5. to hold onto, hold on, stick; 6. to maintain, take care of"
  },
  {
    "ID": "138",
    "disc": "3",
    "lemma": "kan",
    "etym": "Khmer កាន់ (kan)",
    "etycat": "khmer, austroasiatic",
    "notes": "",
    "derive": "makanigi",
    "cat": "",
    "pos": "verb, intr.",
    "def": "7. (figuratively) to have control over, be the boss"
  },
  {
    "ID": "138",
    "disc": "4",
    "lemma": "kan",
    "etym": "Khmer កាន់ (kan)",
    "etycat": "khmer, austroasiatic",
    "notes": "",
    "derive": "makanigi",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "8. (figuratively) to understand, grasp"
  },
  {
    "ID": "138",
    "disc": "5",
    "lemma": "kan",
    "etym": "Khmer កាន់ (kan)",
    "etycat": "khmer, austroasiatic",
    "notes": "",
    "derive": "makanigi",
    "cat": "body, limbs, body parts, video games, games",
    "pos": "noun",
    "def": "9. hand, palm; 10. (figuratively) power, control, possession; 11. (chiefly plural) controls (of a game)"
  },
  {
    "ID": "139",
    "disc": "",
    "lemma": "makanigi",
    "etym": "ma- + kan + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb",
    "def": "1. to remove, take off; 2. to let go"
  },
  {
    "ID": "140",
    "disc": "",
    "lemma": "kanan",
    "etym": "Malay kanan",
    "etycat": "malay, malayo-polynesian, austronesian",
    "notes": "when one faces to where the sun rises, south is to the right",
    "derive": "",
    "cat": "directions, cardinal directions",
    "pos": "preposition",
    "def": "1. right, rightward; 2. south"
  },
  {
    "ID": "141",
    "disc": "",
    "lemma": "-lo",
    "etym": "lo",
    "etycat": "baslamo, a priori",
    "notes": "",
    "derive": "nasolo",
    "cat": "",
    "pos": "nominal suffix",
    "def": "1. Creates nouns that denote a tool for performing some action"
  },
  {
    "ID": "142",
    "disc": "",
    "lemma": "nasolo",
    "etym": "naso + -lo",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. writing utensil, pen, pencil, quill"
  },
  {
    "ID": "143",
    "disc": "",
    "lemma": "fasono nasolo",
    "etym": "fasono + nasolo",
    "etycat": "collocation, compound",
    "notes": "",
    "derive": "",
    "cat": "technology",
    "pos": "noun",
    "def": "1. printer"
  },
  {
    "ID": "144",
    "disc": "",
    "lemma": "mua son",
    "etym": "mua + son",
    "etycat": "collocation, compound",
    "notes": "literally \"the first (of the) sun",
    "derive": "",
    "cat": "directions, cardinal directions",
    "pos": "noun",
    "def": "1. east"
  },
  {
    "ID": "145",
    "disc": "",
    "lemma": "jaset son",
    "etym": "jaset + son",
    "etycat": "collocation, compound",
    "notes": "literally \"the last (of the) sun",
    "derive": "",
    "cat": "directions, cardinal directions",
    "pos": "noun",
    "def": "1. west"
  },
  {
    "ID": "146",
    "disc": "",
    "lemma": "-alo",
    "etym": "-lo",
    "etycat": "baslamo, a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "nominal suffix",
    "def": "1. Alternative form of -lo"
  },
  {
    "ID": "147",
    "disc": "1",
    "lemma": "sok",
    "etym": "Tuvan соок",
    "etycat": "tuvan, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to cool, refridgerate"
  },
  {
    "ID": "147",
    "disc": "2",
    "lemma": "sok",
    "etym": "Tuvan соок",
    "etycat": "tuvan, turkic",
    "notes": "",
    "derive": "",
    "cat": "temperature",
    "pos": "adjective",
    "def": "2. cold"
  },
  {
    "ID": "148",
    "disc": "",
    "lemma": "ma-",
    "etym": "ma",
    "etycat": "baslamo, a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "prefix",
    "def": "1. Forms antonyms"
  },
  {
    "ID": "149",
    "disc": "",
    "lemma": "mal-",
    "etym": "ma-",
    "etycat": "alternative forms",
    "notes": "influenced by Esperanto mal-",
    "derive": "",
    "cat": "",
    "pos": "prefix",
    "def": "1. Alternative form of ma- used before vowels"
  },
  {
    "ID": "150",
    "disc": "",
    "lemma": "aba",
    "etym": "German aber",
    "etycat": "german, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "conjunction",
    "def": "1. but, however, on the contrary"
  },
  {
    "ID": "151",
    "disc": "",
    "lemma": "kanu",
    "etym": "Ingrian kanu",
    "etycat": "ingrian, finnic, uralic",
    "notes": "",
    "derive": "",
    "cat": "body parts",
    "pos": "noun",
    "def": "1. face, appearance, visage; 2. shape"
  },
  {
    "ID": "152",
    "disc": "1",
    "lemma": "kelit",
    "etym": "Persian کلید (kelid)",
    "etycat": "persian, iranian, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to unlock"
  },
  {
    "ID": "152",
    "disc": "2",
    "lemma": "kelit",
    "etym": "Persian کلید (kelid)",
    "etycat": "persian, iranian, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "2. to toggle, switch between two states"
  },
  {
    "ID": "152",
    "disc": "3",
    "lemma": "kelit",
    "etym": "Persian کلید (kelid)",
    "etycat": "persian, iranian, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "3. key; 4. switch"
  },
  {
    "ID": "153",
    "disc": "",
    "lemma": "kesek",
    "etym": "Kyrgyz кесек (kesek)",
    "etycat": "kyrgyz, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. piece, bit, chunk, part; 2. role, part, placement, position; 3. lesson, section, unit; 4. chapter"
  },
  {
    "ID": "154",
    "disc": "1",
    "lemma": "kiba",
    "etym": "Hebrew כיבה (kiba)",
    "etycat": "hebrew, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to extinguish, snuff out, put out; 2. to detach, separate, disconnect; 3. to shut off, shut down"
  },
  {
    "ID": "154",
    "disc": "2",
    "lemma": "kiba",
    "etym": "Hebrew כיבה (kiba)",
    "etycat": "hebrew, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "4. extinguished; 5. shut off, offline, down; 6. disconnected"
  },
  {
    "ID": "155",
    "disc": "1",
    "lemma": "un",
    "etym": "Latin unus",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. one, single, once"
  },
  {
    "ID": "155",
    "disc": "2",
    "lemma": "un",
    "etym": "Latin unus",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "2. primary, chief, first"
  },
  {
    "ID": "155",
    "disc": "3",
    "lemma": "un",
    "etym": "Latin unus",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "3. finger"
  },
  {
    "ID": "156",
    "disc": "",
    "lemma": "lua",
    "etym": "Hawaiian lua",
    "etycat": "hawaiian, oceanic, malayo-polynesian, austronesian",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. two, double, twice"
  },
  {
    "ID": "157",
    "disc": "",
    "lemma": "ine",
    "etym": "Ainu イネ (ine)",
    "etycat": "ainu, isolates",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. four"
  },
  {
    "ID": "158",
    "disc": "",
    "lemma": "ses",
    "etym": "Spanish seis, Portuguese seis",
    "etycat": "spanish, portuguese, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. six"
  },
  {
    "ID": "159",
    "disc": "",
    "lemma": "sata",
    "etym": "Punjabi ਸੱਤ (sattă)",
    "etycat": "punjabi, indo-aryan, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. seven"
  },
  {
    "ID": "160",
    "disc": "",
    "lemma": "valu",
    "etym": "Fijian walu",
    "etycat": "fijian, oceanic, malayo-polynesian, austronesian",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. eight"
  },
  {
    "ID": "161",
    "disc": "",
    "lemma": "togus",
    "etym": "Dolgan тогус (togus)",
    "etycat": "dolgan, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. nine"
  },
  {
    "ID": "162",
    "disc": "",
    "lemma": "sip",
    "etym": "Thai สิบ (sip)",
    "etycat": "thai, southwestern tai, kra-dai",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "numeral",
    "def": "1. ten"
  },
  {
    "ID": "163",
    "disc": "1",
    "lemma": "kino",
    "etym": "Greek κινώ (kinó)",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to move, start, go"
  },
  {
    "ID": "163",
    "disc": "2",
    "lemma": "kino",
    "etym": "Greek κινώ (kinó)",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. motion, movement"
  },
  {
    "ID": "164",
    "disc": "1",
    "lemma": "kisa",
    "etym": "Spanish quizá",
    "etycat": "spanish, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to think, believe, assume"
  },
  {
    "ID": "164",
    "disc": "2",
    "lemma": "kisa",
    "etym": "Spanish quizá",
    "etycat": "spanish, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "2. possibly, maybe"
  },
  {
    "ID": "165",
    "disc": "1",
    "lemma": "kitap",
    "etym": "Arabic كتاب (kitāb)",
    "etycat": "arabic, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, ambi.",
    "def": "1. to read"
  },
  {
    "ID": "165",
    "disc": "2",
    "lemma": "kitap",
    "etym": "Arabic كتاب (kitāb)",
    "etycat": "arabic, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. book"
  },
  {
    "ID": "165",
    "disc": "3",
    "lemma": "kitap",
    "etym": "Arabic كتاب (kitāb)",
    "etycat": "arabic, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "3. literally, by the book"
  },
  {
    "ID": "166",
    "disc": "",
    "lemma": "inaki",
    "etym": "Oroch инаки (inaki)",
    "etycat": "oroch, tungusic",
    "notes": "",
    "derive": "",
    "cat": "animals",
    "pos": "noun",
    "def": "1. dog, hound"
  },
  {
    "ID": "167",
    "disc": "",
    "lemma": "koj",
    "etym": "Vietnamese khối",
    "etycat": "vietnamese, vietic, austroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. block, mass; 2. cube"
  },
  {
    "ID": "168",
    "disc": "1",
    "lemma": "kojma",
    "etym": "Bashkir ҡойма (qojma)",
    "etycat": "bashkir, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to fence off, enclose"
  },
  {
    "ID": "168",
    "disc": "2",
    "lemma": "kojma",
    "etym": "Bashkir ҡойма (qojma)",
    "etycat": "bashkir, turkic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. fence, barrier"
  },
  {
    "ID": "169",
    "disc": "",
    "lemma": "koke",
    "etym": "Klamath-Modoc ɢoɢe",
    "etycat": "klamath-modoc, plateau penutian",
    "notes": "",
    "derive": "",
    "cat": "nature, water, geography",
    "pos": "noun",
    "def": "1. river, stream, creek"
  },
  {
    "ID": "170",
    "disc": "1",
    "lemma": "kolon",
    "etym": "Latin corōna",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "planets, days of the week",
    "pos": "noun",
    "def": "1. crown, garlet, wreath; 2. (astronomy) (talkatel~) Saturn; 3. (taga~) Saturday"
  },
  {
    "ID": "170",
    "disc": "2",
    "lemma": "kolon",
    "etym": "Latin corōna",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "4. royal, noble"
  },
  {
    "ID": "171",
    "disc": "",
    "lemma": "komputa",
    "etym": "English computer",
    "etycat": "english, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "technology",
    "pos": "noun",
    "def": "1. computer"
  },
  {
    "ID": "172",
    "disc": "",
    "lemma": "konsol",
    "etym": "English console",
    "etycat": "english, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "technology",
    "pos": "noun",
    "def": "1. console, video game console"
  },
  {
    "ID": "173",
    "disc": "",
    "lemma": "kot",
    "etym": "Mongolian хот (xot)",
    "etycat": "mongolian, mongolic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. city, town, village, settlement"
  },
  {
    "ID": "174",
    "disc": "",
    "lemma": "kuas",
    "etym": "German Quarz",
    "etycat": "german, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "minerals",
    "pos": "noun",
    "def": "1. quartz"
  },
  {
    "ID": "175",
    "disc": "",
    "lemma": "lil",
    "etym": "Estonian lill",
    "etycat": "estonian, finnic, uralic",
    "notes": "",
    "derive": "",
    "cat": "seasons, nature, plants",
    "pos": "noun",
    "def": "1. flower; 2. spring (season)"
  },
  {
    "ID": "176",
    "disc": "",
    "lemma": "tasa",
    "etym": "Panamint tatsa",
    "etycat": "panamint, numic, uto-aztecan",
    "notes": "",
    "derive": "",
    "cat": "seasons",
    "pos": "noun",
    "def": "1. summer"
  },
  {
    "ID": "177",
    "disc": "",
    "lemma": "sato",
    "etym": "Finnish sato",
    "etycat": "finnish, finnic, uralic",
    "notes": "",
    "derive": "",
    "cat": "seasons, plants",
    "pos": "noun",
    "def": "1. crop, field; 2. harvest; 3. autumn"
  },
  {
    "ID": "178",
    "disc": "",
    "lemma": "kus",
    "etym": "Yakut кыс (kïs)",
    "etycat": "yakut, turkic",
    "notes": "",
    "derive": "",
    "cat": "seasons",
    "pos": "noun",
    "def": "1. winter"
  },
  {
    "ID": "179",
    "disc": "",
    "lemma": "l-",
    "etym": "a priori",
    "etycat": "a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative prefix",
    "def": "1. Forms demonstrative correlatives, analogous to \"this\" and \"that\" in English"
  },
  {
    "ID": "180",
    "disc": "",
    "lemma": "s-",
    "etym": "a priori",
    "etycat": "a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative prefix",
    "def": "1. Forms universal correlatives, analogous to \"every\" in English"
  },
  {
    "ID": "181",
    "disc": "",
    "lemma": "m-",
    "etym": "ma",
    "etycat": "baslamo, a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative prefix",
    "def": "1. Forms negative correlaties, analogous to \"no\" or \"none\" in English"
  },
  {
    "ID": "182",
    "disc": "",
    "lemma": "-om",
    "etym": "a priori",
    "etycat": "a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative suffix",
    "def": "1. Forms manner or reason correlatives, analogous to \"way\" or \"how\" in English"
  },
  {
    "ID": "183",
    "disc": "",
    "lemma": "-osi",
    "etym": "si",
    "etycat": "baslamo, a priori",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "correlative suffix",
    "def": "1. Forms time correlatives, analogous to \"when\" in English"
  },
  {
    "ID": "184",
    "disc": "1",
    "lemma": "ladi",
    "etym": "Czech ladit",
    "etycat": "czech, slavic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "instruments, music",
    "pos": "verb, ambi.",
    "def": "1. to tune (an instrument); 2. to customize, tweak"
  },
  {
    "ID": "184",
    "disc": "2",
    "lemma": "ladi",
    "etym": "Czech ladit",
    "etycat": "czech, slavic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "music",
    "pos": "noun",
    "def": "3. temperament, tuning; 4. customization"
  },
  {
    "ID": "185",
    "disc": "1",
    "lemma": "lami",
    "etym": "Arabic لامع (lāmiʕ)",
    "etycat": "arabic, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, intr.",
    "def": "1. to shine, glimmer, sparkle; 2. to fizz"
  },
  {
    "ID": "185",
    "disc": "2",
    "lemma": "lami",
    "etym": "Arabic لامع (lāmiʕ)",
    "etycat": "arabic, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "planets, days of the week",
    "pos": "noun",
    "def": "3. brightness, lightness; 4. (astronomy) (talkatel~) Venus; 5. (taga~) Friday"
  },
  {
    "ID": "185",
    "disc": "3",
    "lemma": "lami",
    "etym": "Arabic لامع (lāmiʕ)",
    "etycat": "arabic, semitic, afroasiatic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjetive",
    "def": "6. radiant, shiny, glistening; 7. fizzy, carbonated"
  },
  {
    "ID": "186",
    "disc": "",
    "lemma": "agagi",
    "etym": "aga + -igi",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to make large, make big; 2. capitalize"
  },
  {
    "ID": "187",
    "disc": "",
    "lemma": "lava",
    "etym": "English lava",
    "etycat": "english, germanic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "geology",
    "pos": "noun",
    "def": "1. lava"
  },
  {
    "ID": "188",
    "disc": "",
    "lemma": "lego",
    "etym": "Greek λέγω (légo)",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "politics",
    "pos": "verb, trans.",
    "def": "1. to choose, pick, select; 2. to elect, delegate, assign, vote for"
  },
  {
    "ID": "189",
    "disc": "",
    "lemma": "leto",
    "etym": "Slovene lẹ́to",
    "etycat": "slovene, slavic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "time",
    "pos": "noun",
    "def": "1. year"
  },
  {
    "ID": "190",
    "disc": "1",
    "lemma": "li",
    "etym": "Toki Pona li",
    "etycat": "toki pona, constructed",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "particle",
    "def": "1. A particle used before verbs to explicitly mark the imperfect aspect"
  },
  {
    "ID": "190",
    "disc": "2",
    "lemma": "li",
    "etym": "Toki Pona li",
    "etycat": "toki pona, constructed",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "interjection",
    "def": "2. A general affirmative answer in the imperfect aspect; yes"
  },
  {
    "ID": "191",
    "disc": "1",
    "lemma": "lom",
    "etym": "Thai ลม (lom)",
    "etycat": "thai, southwestern tai, kra-dai",
    "notes": "",
    "derive": "",
    "cat": "weather",
    "pos": "verb, aval.",
    "def": "1. to be windy, be a windy day"
  },
  {
    "ID": "191",
    "disc": "2",
    "lemma": "lom",
    "etym": "Thai ลม (lom)",
    "etycat": "thai, southwestern tai, kra-dai",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, intr.",
    "def": "2. to be full of life, live"
  },
  {
    "ID": "191",
    "disc": "3",
    "lemma": "lom",
    "etym": "Thai ลม (lom)",
    "etycat": "thai, southwestern tai, kra-dai",
    "notes": "",
    "derive": "",
    "cat": "weather, religion",
    "pos": "noun",
    "def": "3. wind, breeze, air; 4. personality, demeanor, style, attitude; 5. spirit, soul, lifeforce"
  },
  {
    "ID": "192",
    "disc": "",
    "lemma": "luk",
    "etym": "Zhuang lwg",
    "etycat": "zhuang, northern tai, kra-dai",
    "notes": "",
    "derive": "",
    "cat": "people",
    "pos": "noun, gendered",
    "def": "1. kid, baby, offspring; 2. child, son, daughter"
  },
  {
    "ID": "193",
    "disc": "",
    "lemma": "mali",
    "etym": "ma + li",
    "etycat": "compound, lexical compound",
    "notes": "literally \"not-yes",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "1. negative, negatory"
  },
  {
    "ID": "194",
    "disc": "1",
    "lemma": "ma",
    "etym": "Turkish -ma, Arabic ما (mā), and Thai ไม่ (mâi)",
    "etycat": "turkish, turkic, arabic, semitic, afroasiatic, thai, southwestern tai, kra-dai",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "particle",
    "def": "1. General negation particle, not"
  },
  {
    "ID": "194",
    "disc": "2",
    "lemma": "ma",
    "etym": "Turkish -ma, Arabic ما (mā), and Thai ไม่ (mâi)",
    "etycat": "turkish, turkic, arabic, semitic, afroasiatic, thai, southwestern tai, kra-dai",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "interjection",
    "def": "2. no, nuh-uh, nah"
  },
  {
    "ID": "195",
    "disc": "1",
    "lemma": "magi",
    "etym": "Latin magīa",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, intr.",
    "def": "1. to use magic, practice magic"
  },
  {
    "ID": "195",
    "disc": "2",
    "lemma": "magi",
    "etym": "Latin magīa",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "2. to cast a spell, incantation"
  },
  {
    "ID": "195",
    "disc": "3",
    "lemma": "magi",
    "etym": "Latin magīa",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "3. magic, spell, sorcery, hex"
  },
  {
    "ID": "195",
    "disc": "4",
    "lemma": "magi",
    "etym": "Latin magīa",
    "etycat": "latin, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "4. magical"
  },
  {
    "ID": "196",
    "disc": "1",
    "lemma": "majs",
    "etym": "Lithuanian maišyti, Latvian maisit",
    "etycat": "lithuanian, latvian, baltic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to stir together, combine, mix; 2. to mingle with, join, become a part of"
  },
  {
    "ID": "196",
    "disc": "2",
    "lemma": "majs",
    "etym": "Lithuanian maišyti, Latvian maisit",
    "etycat": "lithuanian, latvian, baltic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans., u",
    "def": "3. to be inseparable from, be essential to"
  },
  {
    "ID": "196",
    "disc": "3",
    "lemma": "majs",
    "etym": "Lithuanian maišyti, Latvian maisit",
    "etycat": "lithuanian, latvian, baltic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, intr.",
    "def": "4. to mix with one another, combine, dissolve"
  },
  {
    "ID": "196",
    "disc": "4",
    "lemma": "majs",
    "etym": "Lithuanian maišyti, Latvian maisit",
    "etycat": "lithuanian, latvian, baltic, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "5. mixture, combination; 6. collection of diverse things"
  },
  {
    "ID": "197",
    "disc": "",
    "lemma": "dop-basa",
    "etym": "dop + basa",
    "etycat": "compound, lexical compound",
    "notes": "calque of Esperanto helplingvo",
    "derive": "",
    "cat": "languages",
    "pos": "noun",
    "def": "1. international auxiliary language, IAL"
  },
  {
    "ID": "198",
    "disc": "1",
    "lemma": "fas-basa",
    "etym": "fas + basa",
    "etycat": "compound, lexical compound",
    "notes": "",
    "derive": "",
    "cat": "languages",
    "pos": "verb",
    "def": "1. to construct a language, to conlang"
  },
  {
    "ID": "198",
    "disc": "2",
    "lemma": "fas-basa",
    "etym": "fas + basa",
    "etycat": "compound, lexical compound",
    "notes": "",
    "derive": "",
    "cat": "languages",
    "pos": "noun",
    "def": "1. conlang, constructed language"
  },
  {
    "ID": "199",
    "disc": "",
    "lemma": "senet-basa",
    "etym": "senet + basa",
    "etycat": "compound, lexical compound",
    "notes": "",
    "derive": "",
    "cat": "languages",
    "pos": "noun",
    "def": "1. artlang, artistic language; 2. conlang, constructed language (especially of works of fiction)"
  },
  {
    "ID": "200",
    "disc": "",
    "lemma": "imut sin",
    "etym": "imut + sin",
    "etycat": "collocation",
    "notes": "literally \"good to see [you]",
    "derive": "",
    "cat": "",
    "pos": "interjection",
    "def": "1. hello, good to see you, good day"
  },
  {
    "ID": "201",
    "disc": "",
    "lemma": "imut til",
    "etym": "imut + til",
    "etycat": "collocation",
    "notes": "literally \"good coming",
    "derive": "",
    "cat": "",
    "pos": "interjection",
    "def": "1. welcome, hello"
  },
  {
    "ID": "202",
    "disc": "",
    "lemma": "lle",
    "etym": "lel + li + e",
    "etycat": "contraction",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "contraction",
    "def": "1. it exists, it is"
  },
  {
    "ID": "203",
    "disc": "",
    "lemma": "mama",
    "etym": "almost every language",
    "etycat": "many",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun, gendered",
    "def": "1. parent, mother, father"
  },
  {
    "ID": "204",
    "disc": "",
    "lemma": "mameso",
    "etym": "ma + meso, a calque of Greek άμεσος (ámesos) \"without a middle",
    "etycat": "greek, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "1. direct, swift, fast"
  },
  {
    "ID": "205",
    "disc": "",
    "lemma": "me",
    "etym": "the chapter M-T pronouns in WALS",
    "etycat": "many",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "pronoun",
    "def": "1. I, me; 2. us"
  },
  {
    "ID": "206",
    "disc": "",
    "lemma": "mea",
    "etym": "me + -a",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "pronoun",
    "def": "1. my, mine; 2. our, ours"
  },
  {
    "ID": "207",
    "disc": "",
    "lemma": "te",
    "etym": "the chapter M-T pronouns in WALS",
    "etycat": "many",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "pronoun",
    "def": "1. you; 2. y'all"
  },
  {
    "ID": "208",
    "disc": "",
    "lemma": "tea",
    "etym": "te + -a",
    "etycat": "compound, derivation",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "pronoun",
    "def": "1. your; 2. y'all's"
  },
  {
    "ID": "209",
    "disc": "1",
    "lemma": "medegi",
    "etym": "Georgian მედეგი (medegi)",
    "etycat": "georgian, kartvelian",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to keep safe, fortify, protect"
  },
  {
    "ID": "209",
    "disc": "2",
    "lemma": "medegi",
    "etym": "Georgian მედეგი (medegi)",
    "etycat": "georgian, kartvelian",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "2. strength, stability; 3. fortification, protection"
  },
  {
    "ID": "209",
    "disc": "3",
    "lemma": "medegi",
    "etym": "Georgian მედეგი (medegi)",
    "etycat": "georgian, kartvelian",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "4. stable, steady, fixed, unchanging; 5. strong; 6. surely, definitely"
  },
  {
    "ID": "210",
    "disc": "",
    "lemma": "meligi",
    "etym": "mel + -igi",
    "etycat": "compound, derivation",
    "notes": "literally \"to cause to be nothing",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to delete, get rid of, throw out"
  },
  {
    "ID": "211",
    "disc": "1",
    "lemma": "mena",
    "etym": "Spanish mena",
    "etycat": "",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. ore, mineral, gemstone"
  },
  {
    "ID": "211",
    "disc": "2",
    "lemma": "mena",
    "etym": "Spanish mena",
    "etycat": "",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "2. valuable, expensive"
  },
  {
    "ID": "212",
    "disc": "1",
    "lemma": "meso",
    "etym": "Greek μέσο (méso)",
    "etycat": "",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. middle, center, midpoint; 2. origin, source"
  },
  {
    "ID": "212",
    "disc": "2",
    "lemma": "meso",
    "etym": "Greek μέσο (méso)",
    "etycat": "",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "preposition",
    "def": "3. center, middle, midpoint; 4. in between"
  },
  {
    "ID": "213",
    "disc": "1",
    "lemma": "meti",
    "etym": "Friulian meti",
    "etycat": "friulian, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "verb, trans.",
    "def": "1. to place down, set, place; 2. to add, append"
  },
  {
    "ID": "213",
    "disc": "2",
    "lemma": "meti",
    "etym": "Friulian meti",
    "etycat": "friulian, romance, indo-european",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "3. place, location"
  },
  {
    "ID": "214",
    "disc": "1",
    "lemma": "ono",
    "etym": "Japanese 己 [おの] (ono)",
    "etycat": "japanese, japonic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "noun",
    "def": "1. the self, oneself"
  },
  {
    "ID": "214",
    "disc": "2",
    "lemma": "ono",
    "etym": "Japanese 己 [おの] (ono)",
    "etycat": "japanese, japonic",
    "notes": "",
    "derive": "",
    "cat": "",
    "pos": "adjective",
    "def": "2. alone, by oneself"
  }
]